alias: Chiudi tenda e tapparella quando parte un film
description: >-
  Chiude tenda Velux e tapparella se Apple TV riproduce un film in app
  whitelisted e la luminosità è alta.
triggers:
  - entity_id: media_player.tv
    to: playing
    for: "00:00:05"
    trigger: state
conditions:
  - condition: numeric_state
    entity_id: sensor.sensore_di_luminosita_soggiorno
    above: 120
  - condition: template
    value_template: >
      {% set app = (state_attr('media_player.tv', 'app_name') or '') | string %}
      {% set ok_apps = ['TV','Apple TV','Prime
      Video','Infuse','Disney+','Netflix'] %} {{ app in ok_apps }}
  - condition: template
    value_template: >
      {{ (state_attr('media_player.tv','media_content_type') or '') | lower ==
      'movie' }}
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: |
              {{ states('cover.tenda_velux_soggiorno') != 'closed' }}
        sequence:
          - target:
              entity_id: cover.tenda_velux_soggiorno
            action: cover.close_cover
  - choose:
      - conditions:
          - condition: template
            value_template: |
              {{ states('cover.tapparella_soggiorno') != 'closed' }}
        sequence:
          - target:
              entity_id: cover.tapparella_soggiorno
            action: cover.close_cover
mode: single
