alias: Simple Light Automation
description: Turn on light when motion detected
trigger:
  - platform: state
    entity_id: binary_sensor.motion_sensor
    to: "on"
action:
  - service: light.turn_on
    target:
      entity_id: light.living_room
mode: single
