alias: Adaptive Lighting Quando Accendo Luci
description: ""
triggers:
  - domain: knx
    device_id: ee504a40b987814032d9ec9c29b1a43f
    type: telegram
    group_value_write: true
    incoming: true
    destination:
      - 2/4/7
      - 2/4/3
      - 2/4/4
      - 2/4/5
      - 2/4/6
      - 0/0/191
      - 0/0/142
      - 0/0/248
      - 0/0/1
    trigger: device
conditions:
  - condition: template
    value_template: "{{ trigger.payload == 1 }}"
actions:
  - condition: template
    value_template: "{{ target_light is not none }}"
  - wait_template: "{{ is_state(target_light, 'on') }}"
    timeout: "00:00:03"
  - condition: template
    value_template: "{{ is_state(target_light, 'on') }}"
  - target:
      entity_id: "{{ target_light }}"
    data:
      brightness_pct: 100
      transition: 0
    action: light.turn_on
  - delay:
      milliseconds: 500
  - variables:
      color_before: >-
        {% set a = state_attr(target_light, 'hs_color') %} {% set b =
        state_attr(target_light, 'xy_color') %} {% set c =
        state_attr(target_light, 'color_temp_kelvin') %} {% set d =
        state_attr(target_light, 'color_temp') %} {{ [a, b, c, d] }}
  - data:
      entity_id: switch.adaptive_lighting_adapt_color_dali
      lights:
        - "{{ target_light }}"
      turn_on_lights: false
      adapt_brightness: false
      adapt_color: true
      transition: 0
    action: adaptive_lighting.apply
  - delay:
      milliseconds: 350
  - variables:
      color_after_1: >-
        {% set a = state_attr(target_light, 'hs_color') %} {% set b =
        state_attr(target_light, 'xy_color') %} {% set c =
        state_attr(target_light, 'color_temp_kelvin') %} {% set d =
        state_attr(target_light, 'color_temp') %} {{ [a, b, c, d] }}
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ is_state(target_light, 'on') and (color_after_1 ==
              color_before) }}
        sequence:
          - data:
              entity_id: switch.adaptive_lighting_adapt_color_dali
              lights:
                - "{{ target_light }}"
              turn_on_lights: false
              adapt_brightness: false
              adapt_color: true
              transition: 0
            action: adaptive_lighting.apply
          - delay:
              milliseconds: 350
  - variables:
      color_after_2: >-
        {% set a = state_attr(target_light, 'hs_color') %} {% set b =
        state_attr(target_light, 'xy_color') %} {% set c =
        state_attr(target_light, 'color_temp_kelvin') %} {% set d =
        state_attr(target_light, 'color_temp') %} {{ [a, b, c, d] }}
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ is_state(target_light, 'on') and (color_after_2 ==
              color_before) }}
        sequence:
          - data:
              entity_id: switch.adaptive_lighting_adapt_color_dali
              lights:
                - "{{ target_light }}"
              turn_on_lights: false
              adapt_brightness: false
              adapt_color: true
              transition: 0
            action: adaptive_lighting.apply
mode: single
variables:
  ga_to_light:
    2/4/7: light.zona
    2/4/3: light.camera_da_letto
    2/4/4: light.bagno_padronale
    2/4/5: light.cucina
    2/4/6: light.soggiorno
    0/0/191: light.soffitto_studio
    0/0/142: light.soffitto_bagno_di_servizio
    0/0/248: light.lampadario_soggiorno
    0/0/1: light.faretti_disimpegno
  ga: "{{ trigger.destination }}"
  target_light: "{{ ga_to_light.get(ga) }}"
