alias: "DHW: Smart Arrival (Maria)"
description: "Arrival: Heats if cold (after 5h away). Departure: Turns OFF (only if warm)."
triggers:
  - entity_id: person.maria
    zone: zone.city_limits
    event: enter
    id: arriving
    trigger: zone
  - entity_id: person.maria
    zone: zone.city_limits
    event: leave
    id: leaving
    trigger: zone
  - entity_id: water_heater.altherma
    attribute: current_temperature
    above: 33
    id: temp_limit_reached
    trigger: numeric_state
actions:
  - choose:
      - conditions:
          - condition: trigger
            id: arriving
          - condition: template
            value_template: >
              {{ (as_timestamp(now()) -
              as_timestamp(trigger.from_state.last_changed)) > 3600 }}
        sequence:
          - if:
              - condition: numeric_state
                entity_id: water_heater.altherma
                attribute: current_temperature
                above: 39
            then:
              - data:
                  title: 🚿 Hot Water Ready
                  message: Welcome back! There is plenty of hot water waiting for you.
                action: notify.mobile_app_iphone_maria
            else:
              - target:
                  entity_id: water_heater.altherma
                action: water_heater.turn_on
              - data:
                  title: 🚿 Heating Water
                  message: Welcome back! Turning on the water heater now.
                action: notify.mobile_app_iphone_maria
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: leaving
              - condition: trigger
                id: temp_limit_reached
          - condition: numeric_state
            entity_id: water_heater.altherma
            attribute: current_temperature
            above: 33
          - condition: not
            conditions:
              - condition: zone
                entity_id: person.maria
                zone: zone.city_limits
        sequence:
          - target:
              entity_id: water_heater.altherma
            action: water_heater.turn_off
mode: single
